### PR TITLE
add breaking test, fix edge case for replacing browser "main" field

### PR DESCRIPTION
**Pull request by mvayngrib**
**Summary**

fixes edge case for replacing browser "main" field, when "main" field value is a file name rather than a file path

**Test plan**

added breaking test in 1st commit, fix in 2nd commit

### CODE REVIEW

**Comment by jeanlauliac** [comment]
That went under the radar, let me look at this tomorrow.

**Comment by mvayngrib** [comment]
@jeanlauliac great, thanks

**Comment by jeanlauliac** [comment]
Hey @mvayngrib, I'm good with this since it adds a new test and doesn't change the existing behavior for the rest; landing now. However I'm not too familiar with how these fields are supposed to work. Do you have a link to some kind of specification about the `browser` field? If so, we could add a link to the spec in an inline comment. If there's none it sounds like we shall write one and add that to the repo documentation 📝 😄

**Comment by mvayngrib** [comment]
@jeanlauliac this is the spec that browserify and webpack use: https://github.com/defunctzombie/package-browser-field-spec

**Comment by jeanlauliac** [comment]
Thank you for sending that pull request! Lemme know if anything looks off.

**Pull request closed without merging**
